CREATE OR REPLACE FUNCTION GET_VALID_DT (P_DATE IN VARCHAR2, P_FORMAT IN VARCHAR2 )
RETURN DATE IS
  L_DT DATE;
BEGIN
    L_DT := TO_DATE(P_DATE, P_FORMAT );
    RETURN L_DT;
EXCEPTION
    WHEN OTHERS THEN
        RETURN NULL;
END ;
/

GRANT ALL ON GET_VALID_DT TO PUBLIC;
--select GET_VALID_DT('01011990','dd-mm-yyyy') as dt from dual;
