--@./s/space.sql
COL TABLE_NAME      FOR A30 ; 
COL TABLESPACE_NAME FOR A30 ; 
SET LINES 80;
SET PAGES 0 EMBEDDED ON;
SET TERMOUT OFF;
SET FEEDBACK ON;
SET ECHO ON;
SPO ./Table_space_usage.txt;
SELECT TABLE_NAME, B.TABLESPACE_NAME,SUM(BYTES)/1024/1024 "SIZE IN MB"
  FROM USER_SEGMENTS A,USER_TABLES B
 WHERE TABLE_NAME=SEGMENT_NAME
   AND B.TABLESPACE_NAME = '??????????'
 --AND TABLE_NAME LIKE '????????'
 GROUP BY B.TABLESPACE_NAME,TABLE_NAME
 ORDER BY SUM(BYTES) DESC
; 
SPO OFF; 
 
 
