CLEAR BREAK;
CLEAR COL;
BREAK ON INDEX_NAME ON UNIQUENESS SKIP 1;
COLUMN COLUMN_EXPRESSION FORMAT A40;
COLUMN INDEX_NAME        FORMAT A30;
COLUMN COLUMN_NAME       FORMAT A30;
SET VERIFY OFF;
SET LINES 150;
SET PAGES 0 EMBEDDED ON;
COLUMN TB NEW_VALUE TBL;
SET HEADING OFF; 
PROMPT;
SELECT 'Index list for the table :' AS TXT , UPPER('&1.') AS TB FROM DUAL; 
PROMPT;
SET HEADING ON; 
SELECT I.INDEX_NAME, 
       I.UNIQUENESS, 
       C.COLUMN_POSITION,
       C.COLUMN_NAME, 
       F.COLUMN_EXPRESSION
FROM ALL_IND_COLUMNS     C, 
     ALL_INDEXES         I, 
     ALL_IND_EXPRESSIONS F
WHERE I.TABLE_NAME      = '&tbl'
  AND I.INDEX_NAME      = C.INDEX_NAME
  AND I.OWNER           = C.INDEX_OWNER
  AND C.INDEX_OWNER     = F.INDEX_OWNER    (+)
  AND C.INDEX_NAME      = F.INDEX_NAME     (+)
  AND C.TABLE_OWNER     = F.TABLE_OWNER    (+)
  AND C.TABLE_NAME      = F.TABLE_NAME     (+)
  AND C.COLUMN_POSITION = F.COLUMN_POSITION(+)
ORDER BY I.INDEX_NAME, C.COLUMN_POSITION
;
