CLEAR BREAK;
CLEAR COL;
BREAK ON TABLE_NAME ON UNIQUENESS SKIP 1;
COLUMN OWNER             FORMAT A30;
COLUMN TABLE_NAME        FORMAT A30;
COLUMN INDEX_NAME        FORMAT A30;
COLUMN COLUMN_NAME       FORMAT A30;
COLUMN CONSTRAINT_NAME   FORMAT A30;
COLUMN COLUMN_EXPRESSION FORMAT A40;
SET VERIFY OFF;
SET LINES 150;
SET PAGES 0 EMBEDDED ON;
COLUMN TB NEW_VALUE TBL;
SET HEADING OFF;
PROMPT;
SELECT 'Primary Keys list for the table :' AS TXT , UPPER('&1.') AS TB FROM DUAL;
PROMPT;
SET HEADING ON;
 
SELECT I.INDEX_NAME, I.INDEX_TYPE, C.COLUMN_NAME
FROM ALL_INDEXES I, ALL_IND_COLUMNS C
WHERE I.TABLE_NAME = '&&TBL.'
  AND I.UNIQUENESS = 'UNIQUE'
  AND I.TABLE_NAME = C.TABLE_NAME
  AND I.INDEX_NAME = C.INDEX_NAME
;
SELECT CONS.OWNER,
       COLS.CONSTRAINT_NAME,
       CONS.STATUS,
       COLS.POSITION,
       COLS.COLUMN_NAME
  FROM ALL_CONSTRAINTS CONS,
       ALL_CONS_COLUMNS COLS
 WHERE COLS.TABLE_NAME      = '&tbl'
   AND CONS.CONSTRAINT_TYPE IN ( 'U', 'P' )
   AND CONS.OWNER           = COLS.OWNER
   AND CONS.CONSTRAINT_NAME = COLS.CONSTRAINT_NAME
  ORDER BY COLS.TABLE_NAME, COLS.POSITION;
  
